# -*- coding: utf-8 -*-
"""Scrape Cafef.vn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XQNECT_Z1qeBR-vvvwj5SOqZGL6Xobcz
"""

import numpy as np
import pandas as pd
import requests
import zipfile
import io
import datetime

def get_all_csv(url):
    with requests.get('http://images1.cafef.vn/data/20200810/CafeF.SolieuGD.10082020.zip') as r:
        z = zipfile.ZipFile(io.BytesIO(r.content))
        z.extractall()

base_url = 'http://images1.cafef.vn/data/{0}/CafeF.SolieuGD.{1}.zip'

date_ranges = pd.date_range('2020-01-01', '2020-07-31')

def to_1st_date_ranges(x):
    return x.strftime('%Y%m%d')

def to_2nd_date_ranges(x):
    return x.strftime('%d%m%Y')

date_ranges_1 = np.vectorize(to_1st_date_ranges)(date_ranges.date)
date_ranges_2 = np.vectorize(to_1st_date_ranges)(date_ranges.date)

for i in np.arange(0,len(date_ranges)):
    url = base_url.format(date_ranges_1[i], date_ranges_2[i])
    get_all_csv(url)